# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.28

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/crypto/Desktop/meshchain_sim_tls_scale

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/crypto/Desktop/meshchain_sim_tls_scale

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components
.PHONY : list_install_components/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local/fast

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/crypto/Desktop/meshchain_sim_tls_scale/CMakeFiles /home/crypto/Desktop/meshchain_sim_tls_scale//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/crypto/Desktop/meshchain_sim_tls_scale/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named meshchain_sim

# Build rule for target.
meshchain_sim: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 meshchain_sim
.PHONY : meshchain_sim

# fast build rule for target.
meshchain_sim/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/meshchain_sim.dir/build.make CMakeFiles/meshchain_sim.dir/build
.PHONY : meshchain_sim/fast

#=============================================================================
# Target rules for targets named meshchain_integrated

# Build rule for target.
meshchain_integrated: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 meshchain_integrated
.PHONY : meshchain_integrated

# fast build rule for target.
meshchain_integrated/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/meshchain_integrated.dir/build.make CMakeFiles/meshchain_integrated.dir/build
.PHONY : meshchain_integrated/fast

#=============================================================================
# Target rules for targets named meshchain_rural

# Build rule for target.
meshchain_rural: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 meshchain_rural
.PHONY : meshchain_rural

# fast build rule for target.
meshchain_rural/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/meshchain_rural.dir/build.make CMakeFiles/meshchain_rural.dir/build
.PHONY : meshchain_rural/fast

#=============================================================================
# Target rules for targets named meshchain_integrated_attack

# Build rule for target.
meshchain_integrated_attack: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 meshchain_integrated_attack
.PHONY : meshchain_integrated_attack

# fast build rule for target.
meshchain_integrated_attack/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/meshchain_integrated_attack.dir/build.make CMakeFiles/meshchain_integrated_attack.dir/build
.PHONY : meshchain_integrated_attack/fast

#=============================================================================
# Target rules for targets named test_zkp

# Build rule for target.
test_zkp: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test_zkp
.PHONY : test_zkp

# fast build rule for target.
test_zkp/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_zkp.dir/build.make CMakeFiles/test_zkp.dir/build
.PHONY : test_zkp/fast

#=============================================================================
# Target rules for targets named benchmark_pqc

# Build rule for target.
benchmark_pqc: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 benchmark_pqc
.PHONY : benchmark_pqc

# fast build rule for target.
benchmark_pqc/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/benchmark_pqc.dir/build.make CMakeFiles/benchmark_pqc.dir/build
.PHONY : benchmark_pqc/fast

#=============================================================================
# Target rules for targets named l2_anchor_watcher

# Build rule for target.
l2_anchor_watcher: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 l2_anchor_watcher
.PHONY : l2_anchor_watcher

# fast build rule for target.
l2_anchor_watcher/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/l2_anchor_watcher.dir/build.make CMakeFiles/l2_anchor_watcher.dir/build
.PHONY : l2_anchor_watcher/fast

#=============================================================================
# Target rules for targets named test_tls13

# Build rule for target.
test_tls13: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test_tls13
.PHONY : test_tls13

# fast build rule for target.
test_tls13/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_tls13.dir/build.make CMakeFiles/test_tls13.dir/build
.PHONY : test_tls13/fast

#=============================================================================
# Target rules for targets named verify_crypto

# Build rule for target.
verify_crypto: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 verify_crypto
.PHONY : verify_crypto

# fast build rule for target.
verify_crypto/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/verify_crypto.dir/build.make CMakeFiles/verify_crypto.dir/build
.PHONY : verify_crypto/fast

#=============================================================================
# Target rules for targets named test_offchain_storage

# Build rule for target.
test_offchain_storage: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test_offchain_storage
.PHONY : test_offchain_storage

# fast build rule for target.
test_offchain_storage/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_offchain_storage.dir/build.make CMakeFiles/test_offchain_storage.dir/build
.PHONY : test_offchain_storage/fast

#=============================================================================
# Target rules for targets named test_shamir_key

# Build rule for target.
test_shamir_key: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test_shamir_key
.PHONY : test_shamir_key

# fast build rule for target.
test_shamir_key/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_shamir_key.dir/build.make CMakeFiles/test_shamir_key.dir/build
.PHONY : test_shamir_key/fast

#=============================================================================
# Target rules for targets named attack_scenario_test

# Build rule for target.
attack_scenario_test: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 attack_scenario_test
.PHONY : attack_scenario_test

# fast build rule for target.
attack_scenario_test/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/attack_scenario_test.dir/build.make CMakeFiles/attack_scenario_test.dir/build
.PHONY : attack_scenario_test/fast

#=============================================================================
# Target rules for targets named test_merkle_proof

# Build rule for target.
test_merkle_proof: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test_merkle_proof
.PHONY : test_merkle_proof

# fast build rule for target.
test_merkle_proof/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_merkle_proof.dir/build.make CMakeFiles/test_merkle_proof.dir/build
.PHONY : test_merkle_proof/fast

#=============================================================================
# Target rules for targets named test_falcon_verification

# Build rule for target.
test_falcon_verification: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test_falcon_verification
.PHONY : test_falcon_verification

# fast build rule for target.
test_falcon_verification/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_falcon_verification.dir/build.make CMakeFiles/test_falcon_verification.dir/build
.PHONY : test_falcon_verification/fast

#=============================================================================
# Target rules for targets named test_falcon_integration

# Build rule for target.
test_falcon_integration: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test_falcon_integration
.PHONY : test_falcon_integration

# fast build rule for target.
test_falcon_integration/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_falcon_integration.dir/build.make CMakeFiles/test_falcon_integration.dir/build
.PHONY : test_falcon_integration/fast

#=============================================================================
# Target rules for targets named test_witness_tracking

# Build rule for target.
test_witness_tracking: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test_witness_tracking
.PHONY : test_witness_tracking

# fast build rule for target.
test_witness_tracking/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_witness_tracking.dir/build.make CMakeFiles/test_witness_tracking.dir/build
.PHONY : test_witness_tracking/fast

#=============================================================================
# Target rules for targets named test_defense_resilience

# Build rule for target.
test_defense_resilience: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test_defense_resilience
.PHONY : test_defense_resilience

# fast build rule for target.
test_defense_resilience/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_defense_resilience.dir/build.make CMakeFiles/test_defense_resilience.dir/build
.PHONY : test_defense_resilience/fast

#=============================================================================
# Target rules for targets named test_defense_paper

# Build rule for target.
test_defense_paper: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test_defense_paper
.PHONY : test_defense_paper

# fast build rule for target.
test_defense_paper/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_defense_paper.dir/build.make CMakeFiles/test_defense_paper.dir/build
.PHONY : test_defense_paper/fast

src/attack_scenario_test.o: src/attack_scenario_test.cpp.o
.PHONY : src/attack_scenario_test.o

# target to build an object file
src/attack_scenario_test.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/attack_scenario_test.dir/build.make CMakeFiles/attack_scenario_test.dir/src/attack_scenario_test.cpp.o
.PHONY : src/attack_scenario_test.cpp.o

src/attack_scenario_test.i: src/attack_scenario_test.cpp.i
.PHONY : src/attack_scenario_test.i

# target to preprocess a source file
src/attack_scenario_test.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/attack_scenario_test.dir/build.make CMakeFiles/attack_scenario_test.dir/src/attack_scenario_test.cpp.i
.PHONY : src/attack_scenario_test.cpp.i

src/attack_scenario_test.s: src/attack_scenario_test.cpp.s
.PHONY : src/attack_scenario_test.s

# target to generate assembly for a file
src/attack_scenario_test.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/attack_scenario_test.dir/build.make CMakeFiles/attack_scenario_test.dir/src/attack_scenario_test.cpp.s
.PHONY : src/attack_scenario_test.cpp.s

src/benchmark_pqc.o: src/benchmark_pqc.cpp.o
.PHONY : src/benchmark_pqc.o

# target to build an object file
src/benchmark_pqc.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/benchmark_pqc.dir/build.make CMakeFiles/benchmark_pqc.dir/src/benchmark_pqc.cpp.o
.PHONY : src/benchmark_pqc.cpp.o

src/benchmark_pqc.i: src/benchmark_pqc.cpp.i
.PHONY : src/benchmark_pqc.i

# target to preprocess a source file
src/benchmark_pqc.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/benchmark_pqc.dir/build.make CMakeFiles/benchmark_pqc.dir/src/benchmark_pqc.cpp.i
.PHONY : src/benchmark_pqc.cpp.i

src/benchmark_pqc.s: src/benchmark_pqc.cpp.s
.PHONY : src/benchmark_pqc.s

# target to generate assembly for a file
src/benchmark_pqc.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/benchmark_pqc.dir/build.make CMakeFiles/benchmark_pqc.dir/src/benchmark_pqc.cpp.s
.PHONY : src/benchmark_pqc.cpp.s

src/l2_anchor_watcher.o: src/l2_anchor_watcher.cpp.o
.PHONY : src/l2_anchor_watcher.o

# target to build an object file
src/l2_anchor_watcher.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/l2_anchor_watcher.dir/build.make CMakeFiles/l2_anchor_watcher.dir/src/l2_anchor_watcher.cpp.o
.PHONY : src/l2_anchor_watcher.cpp.o

src/l2_anchor_watcher.i: src/l2_anchor_watcher.cpp.i
.PHONY : src/l2_anchor_watcher.i

# target to preprocess a source file
src/l2_anchor_watcher.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/l2_anchor_watcher.dir/build.make CMakeFiles/l2_anchor_watcher.dir/src/l2_anchor_watcher.cpp.i
.PHONY : src/l2_anchor_watcher.cpp.i

src/l2_anchor_watcher.s: src/l2_anchor_watcher.cpp.s
.PHONY : src/l2_anchor_watcher.s

# target to generate assembly for a file
src/l2_anchor_watcher.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/l2_anchor_watcher.dir/build.make CMakeFiles/l2_anchor_watcher.dir/src/l2_anchor_watcher.cpp.s
.PHONY : src/l2_anchor_watcher.cpp.s

src/main.o: src/main.cpp.o
.PHONY : src/main.o

# target to build an object file
src/main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/meshchain_sim.dir/build.make CMakeFiles/meshchain_sim.dir/src/main.cpp.o
.PHONY : src/main.cpp.o

src/main.i: src/main.cpp.i
.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/meshchain_sim.dir/build.make CMakeFiles/meshchain_sim.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s
.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/meshchain_sim.dir/build.make CMakeFiles/meshchain_sim.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

src/main_integrated.o: src/main_integrated.cpp.o
.PHONY : src/main_integrated.o

# target to build an object file
src/main_integrated.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/meshchain_integrated.dir/build.make CMakeFiles/meshchain_integrated.dir/src/main_integrated.cpp.o
.PHONY : src/main_integrated.cpp.o

src/main_integrated.i: src/main_integrated.cpp.i
.PHONY : src/main_integrated.i

# target to preprocess a source file
src/main_integrated.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/meshchain_integrated.dir/build.make CMakeFiles/meshchain_integrated.dir/src/main_integrated.cpp.i
.PHONY : src/main_integrated.cpp.i

src/main_integrated.s: src/main_integrated.cpp.s
.PHONY : src/main_integrated.s

# target to generate assembly for a file
src/main_integrated.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/meshchain_integrated.dir/build.make CMakeFiles/meshchain_integrated.dir/src/main_integrated.cpp.s
.PHONY : src/main_integrated.cpp.s

src/main_integrated_attack.o: src/main_integrated_attack.cpp.o
.PHONY : src/main_integrated_attack.o

# target to build an object file
src/main_integrated_attack.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/meshchain_integrated_attack.dir/build.make CMakeFiles/meshchain_integrated_attack.dir/src/main_integrated_attack.cpp.o
.PHONY : src/main_integrated_attack.cpp.o

src/main_integrated_attack.i: src/main_integrated_attack.cpp.i
.PHONY : src/main_integrated_attack.i

# target to preprocess a source file
src/main_integrated_attack.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/meshchain_integrated_attack.dir/build.make CMakeFiles/meshchain_integrated_attack.dir/src/main_integrated_attack.cpp.i
.PHONY : src/main_integrated_attack.cpp.i

src/main_integrated_attack.s: src/main_integrated_attack.cpp.s
.PHONY : src/main_integrated_attack.s

# target to generate assembly for a file
src/main_integrated_attack.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/meshchain_integrated_attack.dir/build.make CMakeFiles/meshchain_integrated_attack.dir/src/main_integrated_attack.cpp.s
.PHONY : src/main_integrated_attack.cpp.s

src/main_rural.o: src/main_rural.cpp.o
.PHONY : src/main_rural.o

# target to build an object file
src/main_rural.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/meshchain_rural.dir/build.make CMakeFiles/meshchain_rural.dir/src/main_rural.cpp.o
.PHONY : src/main_rural.cpp.o

src/main_rural.i: src/main_rural.cpp.i
.PHONY : src/main_rural.i

# target to preprocess a source file
src/main_rural.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/meshchain_rural.dir/build.make CMakeFiles/meshchain_rural.dir/src/main_rural.cpp.i
.PHONY : src/main_rural.cpp.i

src/main_rural.s: src/main_rural.cpp.s
.PHONY : src/main_rural.s

# target to generate assembly for a file
src/main_rural.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/meshchain_rural.dir/build.make CMakeFiles/meshchain_rural.dir/src/main_rural.cpp.s
.PHONY : src/main_rural.cpp.s

src/security/attacker_models.o: src/security/attacker_models.cpp.o
.PHONY : src/security/attacker_models.o

# target to build an object file
src/security/attacker_models.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/meshchain_integrated_attack.dir/build.make CMakeFiles/meshchain_integrated_attack.dir/src/security/attacker_models.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/attack_scenario_test.dir/build.make CMakeFiles/attack_scenario_test.dir/src/security/attacker_models.cpp.o
.PHONY : src/security/attacker_models.cpp.o

src/security/attacker_models.i: src/security/attacker_models.cpp.i
.PHONY : src/security/attacker_models.i

# target to preprocess a source file
src/security/attacker_models.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/meshchain_integrated_attack.dir/build.make CMakeFiles/meshchain_integrated_attack.dir/src/security/attacker_models.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/attack_scenario_test.dir/build.make CMakeFiles/attack_scenario_test.dir/src/security/attacker_models.cpp.i
.PHONY : src/security/attacker_models.cpp.i

src/security/attacker_models.s: src/security/attacker_models.cpp.s
.PHONY : src/security/attacker_models.s

# target to generate assembly for a file
src/security/attacker_models.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/meshchain_integrated_attack.dir/build.make CMakeFiles/meshchain_integrated_attack.dir/src/security/attacker_models.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/attack_scenario_test.dir/build.make CMakeFiles/attack_scenario_test.dir/src/security/attacker_models.cpp.s
.PHONY : src/security/attacker_models.cpp.s

src/test_defense_paper.o: src/test_defense_paper.cpp.o
.PHONY : src/test_defense_paper.o

# target to build an object file
src/test_defense_paper.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_defense_paper.dir/build.make CMakeFiles/test_defense_paper.dir/src/test_defense_paper.cpp.o
.PHONY : src/test_defense_paper.cpp.o

src/test_defense_paper.i: src/test_defense_paper.cpp.i
.PHONY : src/test_defense_paper.i

# target to preprocess a source file
src/test_defense_paper.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_defense_paper.dir/build.make CMakeFiles/test_defense_paper.dir/src/test_defense_paper.cpp.i
.PHONY : src/test_defense_paper.cpp.i

src/test_defense_paper.s: src/test_defense_paper.cpp.s
.PHONY : src/test_defense_paper.s

# target to generate assembly for a file
src/test_defense_paper.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_defense_paper.dir/build.make CMakeFiles/test_defense_paper.dir/src/test_defense_paper.cpp.s
.PHONY : src/test_defense_paper.cpp.s

src/test_defense_resilience.o: src/test_defense_resilience.cpp.o
.PHONY : src/test_defense_resilience.o

# target to build an object file
src/test_defense_resilience.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_defense_resilience.dir/build.make CMakeFiles/test_defense_resilience.dir/src/test_defense_resilience.cpp.o
.PHONY : src/test_defense_resilience.cpp.o

src/test_defense_resilience.i: src/test_defense_resilience.cpp.i
.PHONY : src/test_defense_resilience.i

# target to preprocess a source file
src/test_defense_resilience.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_defense_resilience.dir/build.make CMakeFiles/test_defense_resilience.dir/src/test_defense_resilience.cpp.i
.PHONY : src/test_defense_resilience.cpp.i

src/test_defense_resilience.s: src/test_defense_resilience.cpp.s
.PHONY : src/test_defense_resilience.s

# target to generate assembly for a file
src/test_defense_resilience.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_defense_resilience.dir/build.make CMakeFiles/test_defense_resilience.dir/src/test_defense_resilience.cpp.s
.PHONY : src/test_defense_resilience.cpp.s

src/test_falcon_integration.o: src/test_falcon_integration.cpp.o
.PHONY : src/test_falcon_integration.o

# target to build an object file
src/test_falcon_integration.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_falcon_integration.dir/build.make CMakeFiles/test_falcon_integration.dir/src/test_falcon_integration.cpp.o
.PHONY : src/test_falcon_integration.cpp.o

src/test_falcon_integration.i: src/test_falcon_integration.cpp.i
.PHONY : src/test_falcon_integration.i

# target to preprocess a source file
src/test_falcon_integration.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_falcon_integration.dir/build.make CMakeFiles/test_falcon_integration.dir/src/test_falcon_integration.cpp.i
.PHONY : src/test_falcon_integration.cpp.i

src/test_falcon_integration.s: src/test_falcon_integration.cpp.s
.PHONY : src/test_falcon_integration.s

# target to generate assembly for a file
src/test_falcon_integration.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_falcon_integration.dir/build.make CMakeFiles/test_falcon_integration.dir/src/test_falcon_integration.cpp.s
.PHONY : src/test_falcon_integration.cpp.s

src/test_falcon_verification.o: src/test_falcon_verification.cpp.o
.PHONY : src/test_falcon_verification.o

# target to build an object file
src/test_falcon_verification.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_falcon_verification.dir/build.make CMakeFiles/test_falcon_verification.dir/src/test_falcon_verification.cpp.o
.PHONY : src/test_falcon_verification.cpp.o

src/test_falcon_verification.i: src/test_falcon_verification.cpp.i
.PHONY : src/test_falcon_verification.i

# target to preprocess a source file
src/test_falcon_verification.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_falcon_verification.dir/build.make CMakeFiles/test_falcon_verification.dir/src/test_falcon_verification.cpp.i
.PHONY : src/test_falcon_verification.cpp.i

src/test_falcon_verification.s: src/test_falcon_verification.cpp.s
.PHONY : src/test_falcon_verification.s

# target to generate assembly for a file
src/test_falcon_verification.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_falcon_verification.dir/build.make CMakeFiles/test_falcon_verification.dir/src/test_falcon_verification.cpp.s
.PHONY : src/test_falcon_verification.cpp.s

src/test_merkle_proof.o: src/test_merkle_proof.cpp.o
.PHONY : src/test_merkle_proof.o

# target to build an object file
src/test_merkle_proof.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_merkle_proof.dir/build.make CMakeFiles/test_merkle_proof.dir/src/test_merkle_proof.cpp.o
.PHONY : src/test_merkle_proof.cpp.o

src/test_merkle_proof.i: src/test_merkle_proof.cpp.i
.PHONY : src/test_merkle_proof.i

# target to preprocess a source file
src/test_merkle_proof.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_merkle_proof.dir/build.make CMakeFiles/test_merkle_proof.dir/src/test_merkle_proof.cpp.i
.PHONY : src/test_merkle_proof.cpp.i

src/test_merkle_proof.s: src/test_merkle_proof.cpp.s
.PHONY : src/test_merkle_proof.s

# target to generate assembly for a file
src/test_merkle_proof.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_merkle_proof.dir/build.make CMakeFiles/test_merkle_proof.dir/src/test_merkle_proof.cpp.s
.PHONY : src/test_merkle_proof.cpp.s

src/test_offchain_storage.o: src/test_offchain_storage.cpp.o
.PHONY : src/test_offchain_storage.o

# target to build an object file
src/test_offchain_storage.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_offchain_storage.dir/build.make CMakeFiles/test_offchain_storage.dir/src/test_offchain_storage.cpp.o
.PHONY : src/test_offchain_storage.cpp.o

src/test_offchain_storage.i: src/test_offchain_storage.cpp.i
.PHONY : src/test_offchain_storage.i

# target to preprocess a source file
src/test_offchain_storage.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_offchain_storage.dir/build.make CMakeFiles/test_offchain_storage.dir/src/test_offchain_storage.cpp.i
.PHONY : src/test_offchain_storage.cpp.i

src/test_offchain_storage.s: src/test_offchain_storage.cpp.s
.PHONY : src/test_offchain_storage.s

# target to generate assembly for a file
src/test_offchain_storage.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_offchain_storage.dir/build.make CMakeFiles/test_offchain_storage.dir/src/test_offchain_storage.cpp.s
.PHONY : src/test_offchain_storage.cpp.s

src/test_shamir_key.o: src/test_shamir_key.cpp.o
.PHONY : src/test_shamir_key.o

# target to build an object file
src/test_shamir_key.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_shamir_key.dir/build.make CMakeFiles/test_shamir_key.dir/src/test_shamir_key.cpp.o
.PHONY : src/test_shamir_key.cpp.o

src/test_shamir_key.i: src/test_shamir_key.cpp.i
.PHONY : src/test_shamir_key.i

# target to preprocess a source file
src/test_shamir_key.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_shamir_key.dir/build.make CMakeFiles/test_shamir_key.dir/src/test_shamir_key.cpp.i
.PHONY : src/test_shamir_key.cpp.i

src/test_shamir_key.s: src/test_shamir_key.cpp.s
.PHONY : src/test_shamir_key.s

# target to generate assembly for a file
src/test_shamir_key.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_shamir_key.dir/build.make CMakeFiles/test_shamir_key.dir/src/test_shamir_key.cpp.s
.PHONY : src/test_shamir_key.cpp.s

src/test_tls13.o: src/test_tls13.cpp.o
.PHONY : src/test_tls13.o

# target to build an object file
src/test_tls13.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_tls13.dir/build.make CMakeFiles/test_tls13.dir/src/test_tls13.cpp.o
.PHONY : src/test_tls13.cpp.o

src/test_tls13.i: src/test_tls13.cpp.i
.PHONY : src/test_tls13.i

# target to preprocess a source file
src/test_tls13.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_tls13.dir/build.make CMakeFiles/test_tls13.dir/src/test_tls13.cpp.i
.PHONY : src/test_tls13.cpp.i

src/test_tls13.s: src/test_tls13.cpp.s
.PHONY : src/test_tls13.s

# target to generate assembly for a file
src/test_tls13.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_tls13.dir/build.make CMakeFiles/test_tls13.dir/src/test_tls13.cpp.s
.PHONY : src/test_tls13.cpp.s

src/test_witness_tracking.o: src/test_witness_tracking.cpp.o
.PHONY : src/test_witness_tracking.o

# target to build an object file
src/test_witness_tracking.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_witness_tracking.dir/build.make CMakeFiles/test_witness_tracking.dir/src/test_witness_tracking.cpp.o
.PHONY : src/test_witness_tracking.cpp.o

src/test_witness_tracking.i: src/test_witness_tracking.cpp.i
.PHONY : src/test_witness_tracking.i

# target to preprocess a source file
src/test_witness_tracking.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_witness_tracking.dir/build.make CMakeFiles/test_witness_tracking.dir/src/test_witness_tracking.cpp.i
.PHONY : src/test_witness_tracking.cpp.i

src/test_witness_tracking.s: src/test_witness_tracking.cpp.s
.PHONY : src/test_witness_tracking.s

# target to generate assembly for a file
src/test_witness_tracking.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_witness_tracking.dir/build.make CMakeFiles/test_witness_tracking.dir/src/test_witness_tracking.cpp.s
.PHONY : src/test_witness_tracking.cpp.s

src/test_zkp.o: src/test_zkp.cpp.o
.PHONY : src/test_zkp.o

# target to build an object file
src/test_zkp.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_zkp.dir/build.make CMakeFiles/test_zkp.dir/src/test_zkp.cpp.o
.PHONY : src/test_zkp.cpp.o

src/test_zkp.i: src/test_zkp.cpp.i
.PHONY : src/test_zkp.i

# target to preprocess a source file
src/test_zkp.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_zkp.dir/build.make CMakeFiles/test_zkp.dir/src/test_zkp.cpp.i
.PHONY : src/test_zkp.cpp.i

src/test_zkp.s: src/test_zkp.cpp.s
.PHONY : src/test_zkp.s

# target to generate assembly for a file
src/test_zkp.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_zkp.dir/build.make CMakeFiles/test_zkp.dir/src/test_zkp.cpp.s
.PHONY : src/test_zkp.cpp.s

src/verify_crypto.o: src/verify_crypto.cpp.o
.PHONY : src/verify_crypto.o

# target to build an object file
src/verify_crypto.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/verify_crypto.dir/build.make CMakeFiles/verify_crypto.dir/src/verify_crypto.cpp.o
.PHONY : src/verify_crypto.cpp.o

src/verify_crypto.i: src/verify_crypto.cpp.i
.PHONY : src/verify_crypto.i

# target to preprocess a source file
src/verify_crypto.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/verify_crypto.dir/build.make CMakeFiles/verify_crypto.dir/src/verify_crypto.cpp.i
.PHONY : src/verify_crypto.cpp.i

src/verify_crypto.s: src/verify_crypto.cpp.s
.PHONY : src/verify_crypto.s

# target to generate assembly for a file
src/verify_crypto.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/verify_crypto.dir/build.make CMakeFiles/verify_crypto.dir/src/verify_crypto.cpp.s
.PHONY : src/verify_crypto.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... install"
	@echo "... install/local"
	@echo "... install/strip"
	@echo "... list_install_components"
	@echo "... rebuild_cache"
	@echo "... attack_scenario_test"
	@echo "... benchmark_pqc"
	@echo "... l2_anchor_watcher"
	@echo "... meshchain_integrated"
	@echo "... meshchain_integrated_attack"
	@echo "... meshchain_rural"
	@echo "... meshchain_sim"
	@echo "... test_defense_paper"
	@echo "... test_defense_resilience"
	@echo "... test_falcon_integration"
	@echo "... test_falcon_verification"
	@echo "... test_merkle_proof"
	@echo "... test_offchain_storage"
	@echo "... test_shamir_key"
	@echo "... test_tls13"
	@echo "... test_witness_tracking"
	@echo "... test_zkp"
	@echo "... verify_crypto"
	@echo "... src/attack_scenario_test.o"
	@echo "... src/attack_scenario_test.i"
	@echo "... src/attack_scenario_test.s"
	@echo "... src/benchmark_pqc.o"
	@echo "... src/benchmark_pqc.i"
	@echo "... src/benchmark_pqc.s"
	@echo "... src/l2_anchor_watcher.o"
	@echo "... src/l2_anchor_watcher.i"
	@echo "... src/l2_anchor_watcher.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
	@echo "... src/main_integrated.o"
	@echo "... src/main_integrated.i"
	@echo "... src/main_integrated.s"
	@echo "... src/main_integrated_attack.o"
	@echo "... src/main_integrated_attack.i"
	@echo "... src/main_integrated_attack.s"
	@echo "... src/main_rural.o"
	@echo "... src/main_rural.i"
	@echo "... src/main_rural.s"
	@echo "... src/security/attacker_models.o"
	@echo "... src/security/attacker_models.i"
	@echo "... src/security/attacker_models.s"
	@echo "... src/test_defense_paper.o"
	@echo "... src/test_defense_paper.i"
	@echo "... src/test_defense_paper.s"
	@echo "... src/test_defense_resilience.o"
	@echo "... src/test_defense_resilience.i"
	@echo "... src/test_defense_resilience.s"
	@echo "... src/test_falcon_integration.o"
	@echo "... src/test_falcon_integration.i"
	@echo "... src/test_falcon_integration.s"
	@echo "... src/test_falcon_verification.o"
	@echo "... src/test_falcon_verification.i"
	@echo "... src/test_falcon_verification.s"
	@echo "... src/test_merkle_proof.o"
	@echo "... src/test_merkle_proof.i"
	@echo "... src/test_merkle_proof.s"
	@echo "... src/test_offchain_storage.o"
	@echo "... src/test_offchain_storage.i"
	@echo "... src/test_offchain_storage.s"
	@echo "... src/test_shamir_key.o"
	@echo "... src/test_shamir_key.i"
	@echo "... src/test_shamir_key.s"
	@echo "... src/test_tls13.o"
	@echo "... src/test_tls13.i"
	@echo "... src/test_tls13.s"
	@echo "... src/test_witness_tracking.o"
	@echo "... src/test_witness_tracking.i"
	@echo "... src/test_witness_tracking.s"
	@echo "... src/test_zkp.o"
	@echo "... src/test_zkp.i"
	@echo "... src/test_zkp.s"
	@echo "... src/verify_crypto.o"
	@echo "... src/verify_crypto.i"
	@echo "... src/verify_crypto.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

